[package]
name = "fluent-resmgr"
description = """
Resource manager for Fluent localization resources.
"""
version = "0.0.5"
authors = [
    "Zibi Braniecki <gandalf@mozilla.com>",
    "Staś Małolepszy <stas@mozilla.com>"
]
edition = "2018"
homepage = "http://www.projectfluent.org"
license = "Apache-2.0/MIT"
repository = "https://github.com/projectfluent/fluent-rs"
readme = "README.md"
keywords = ["localization", "l10n", "i18n", "intl", "internationalization"]
categories = ["localization", "internationalization"]

[dependencies]
fluent-bundle = { path = "../fluent-bundle" }
fluent-fallback = { path = "../fluent-fallback" }
unic-langid = "0.9"
elsa = "1.3.2"
futures = "0.3"

[dev-dependencies]
unic-langid = { version = "0.9", features = ["macros"]}
fluent-langneg = "0.13"
