[package]
name = "fluent-resmgr"
description = """
Resource manager for Fluent localization resources.
"""
version = "0.0.6"
authors = [
    "Zibi Braniecki <gandalf@mozilla.com>",
    "Staś Małolepszy <stas@mozilla.com>"
]
edition = "2021"
homepage = "http://www.projectfluent.org"
license = "Apache-2.0 OR MIT"
repository = "https://github.com/projectfluent/fluent-rs"
readme = "README.md"
keywords = ["localization", "l10n", "i18n", "intl", "internationalization"]
categories = ["localization", "internationalization"]

[dependencies]
fluent-bundle.workspace = true
fluent-fallback.workspace = true
futures.workspace = true
rustc-hash.workspace = true
thiserror.workspace = true
unic-langid.workspace = true
elsa = "1.5"

[dev-dependencies]
fluent-langneg.workspace = true
unic-langid = { workspace = true, features = ["macros"] }
