[package]
name = "intl-memoizer"
version = "0.2.0"
authors = [
    "Zibi Braniecki <gandalf@mozilla.com>",
    "Manish Goregaokar <manishsmail@gmail.com>"
]
description = """
A memoizer specifically tailored for storing lazy-initialized
intl formatters.
"""
edition = "2018"
homepage = "http://www.projectfluent.org"
license = "Apache-2.0/MIT"
repository = "https://github.com/projectfluent/fluent-rs"
readme = "README.md"
keywords = ["localization", "l10n", "i18n", "intl", "internationalization"]
categories = ["localization", "internationalization"]

[dependencies]
typemap = "0.3"
unic-langid = "0.8"
fluent-langneg = "0.12"

[dev-dependencies]
intl_pluralrules = "6.0"
