[package]
name = "intl-memoizer"
description = """
A memoizer specifically tailored for storing lazy-initialized
intl formatters.
"""
version = "0.4.0"
edition = "2018"
authors = [
    "Zibi Braniecki <gandalf@mozilla.com>",
    "Manish Goregaokar <manishsmail@gmail.com>"
]
homepage = "http://www.projectfluent.org"
license = "Apache-2.0/MIT"
repository = "https://github.com/projectfluent/fluent-rs"
readme = "README.md"
keywords = ["localization", "l10n", "i18n", "intl", "internationalization"]
categories = ["localization", "internationalization"]
include = [
	"src/**/*",
	"benches/*.rs",
	"Cargo.toml",
	"README.md"
]

[dependencies]
type-map = "0.3"
unic-langid = "0.8"

[dev-dependencies]
intl_pluralrules = "6.0"
fluent-langneg = "0.12"
